- src/main/java/org/terasology/combatSystem/world/PhysicsRoomRasterizer.java
Added different angled walls, a tree, a cube of water and flora that are to be used in testing at later stages.
2 basic NPCs are left.
Don't want to waste time on world gen so I hardcoded everything in a single rasterizer.
@portokaliu and @Cervator Please verify and merge the changes.
> added tree, walls, cube of water and flora to physics room world gen

- assets/prefabs/arrow.prefab
- assets/prefabs/staticCharacter.prefab
- src/main/java/org/terasology/combatSystem/weaponFeatures/components/LaunchEntityComponent.java
- src/main/java/org/terasology/combatSystem/weaponFeatures/systems/LaunchEntitySystem.java
- src/main/java/org/terasology/combatSystem/world/NPCSpawnSystem.java
commit works but the arrows get spawned at (0,0,0) instead of player location
> collision with ground and impulse works for arrows

- src/main/java/org/terasology/combatSystem/physics/systems/CombatPhysicsSystem.java
- src/main/java/org/terasology/combatSystem/weaponFeatures/systems/LaunchEntitySystem.java
- src/main/java/org/terasology/combatSystem/world/NPCSpawnSystem.java
Simple package change in the engine. See MovingBlocks/Terasology#3199
> API adjustments for https://github.com/MovingBlocks/Terasology/pull/3199

- module.txt
- src/main/java/org/terasology/combatSystem/world/structures/StructuresHandlingSystem.java
This PR consists of changes required to work with the animated ST construction implemented in this PR Terasology/StructureTemplates#27.
> Resolve compile error

- src/main/java/org/terasology/combatSystem/world/PhysicsRoomRasterizer.java
One of the affected module in PR MovingBlocks/Terasology#3495
> Removed references of liquidData from PhysicsRoomRasterizer

- src/main/java/org/terasology/combatSystem/inventory/QuiverUIClientSystem.java
Fixes #33 
**To test:**
- Start two instances
- Equip or unequip a weapon with the quiver
- Quiver visibility in the other client is unaffected
> Decouple quiver systems

- src/main/java/org/terasology/combatSystem/hurting/HurtingHandlingSystem.java
API Changes introduced in https://github.com/MovingBlocks/Terasology/pull/3677 and [Health module](https://github.com/Terasology/Health)
> Update to depend on Health module

- src/main/java/org/terasology/combatSystem/hurting/HurtingHandlingSystem.java
- src/main/java/org/terasology/combatSystem/weaponFeatures/events/PrimaryAttackEvent.java
- src/main/java/org/terasology/combatSystem/weaponFeatures/systems/AttackSystem.java
To Test: Create a server with the Combat System mode. Join with another client. Attack with any weapon. Knock-back is observed.
> feat: Add knock-back on attack

- src/main/java/org/terasology/combatSystem/physics/systems/CombatPhysicsSystem.java
- src/main/java/org/terasology/combatSystem/weaponFeatures/systems/LaunchEntitySystem.java
- src/main/java/org/terasology/combatSystem/weaponFeatures/systems/LegacyShootSystem.java
- src/main/java/org/terasology/combatSystem/weaponFeatures/systems/collisionHandling/BouncingHandlingSystem.java
- src/main/java/org/terasology/combatSystem/world/NPCSpawnSystem.java
issue: https://github.com/MovingBlocks/Terasology/pull/4139
> feat: migrate JOML physics

- src/main/java/org/terasology/combatSystem/weaponFeatures/events/PrimaryAttackEvent.java
- src/main/java/org/terasology/combatSystem/weaponFeatures/systems/LegacyShootSystem.java
PR: https://github.com/MovingBlocks/Terasology/pull/4172
> feat(JOML): migrate action event

- src/main/java/org/terasology/combatSystem/world/structures/StructuresHandlingSystem.java
- src/main/java/org/terasology/combatSystem/world/structures/components/AddSwitchDoorsComponent.java
PR: https://github.com/Terasology/StructureTemplates/pull/45
> feat(JOML): migrate joml structured templates

- src/main/java/org/terasology/combatSystem/world/structures/StructuresHandlingSystem.java
Adapt to changes in MovingBlocks/Terasology#4272
> fix: adapt to changes to BlockRegionIterable #73

- src/main/java/org/terasology/combatSystem/weaponFeatures/systems/AttackSystem.java
https://github.com/MovingBlocks/Terasology/pull/4279
> chore(JOML): align `AttackSystem`

- src/main/java/org/terasology/combatSystem/weaponFeatures/systems/AttackSystem.java
PR: https://github.com/MovingBlocks/Terasology/pull/4303
> feat(JOML): migrate AttackSystem

- module.txt
- src/main/java/org/terasology/combatSystem/world/structures/StructuresHandlingSystem.java
Adjust to MovingBlocks/Terasology#4321 and MovingBlocks/Terasology#4326
> feat(BlockRegion): adjust for changes to BlockRegion

- src/main/java/org/terasology/combatSystem/world/PhysicsRoomWorldGenerator.java
Adjust for MovingBlocks/Terasology#4380
> chore(joml): migrate WorldGenerator#getSpawnPosition

- src/main/java/org/terasology/combatSystem/weaponFeatures/systems/collisionHandling/ExplosionHandlingSystem.java
PR: https://github.com/MovingBlocks/Terasology/pull/4413
> feat(JOML): migrate joml to 1.10.0 and 1.0.0-SNAPSHOT for geometry

- src/main/java/org/terasology/combatSystem/weaponFeatures/systems/LaunchEntitySystem.java
PR: https://github.com/MovingBlocks/Terasology/pull/4415
> feat(JOML): migrate Mesh AABBf

- src/main/java/org/terasology/combatSystem/hurting/HurtingHandlingSystem.java
- src/main/java/org/terasology/combatSystem/inventory/QuiverUIClientSystem.java
- src/main/java/org/terasology/combatSystem/physics/components/CollisionExceptionsComponent.java
- src/main/java/org/terasology/combatSystem/physics/events/AddCollisionExceptionEvent.java
- src/main/java/org/terasology/combatSystem/physics/events/RemoveCollisionExceptionEvent.java
- src/main/java/org/terasology/combatSystem/physics/events/ReplaceCollisionExceptionEvent.java
- src/main/java/org/terasology/combatSystem/physics/systems/CollisionExceptionsHandlingSystem.java
- src/main/java/org/terasology/combatSystem/traps/components/SwitchComponent.java
- src/main/java/org/terasology/combatSystem/traps/systems/TrapPlacingSystem.java
- src/main/java/org/terasology/combatSystem/weaponFeatures/components/ArrowComponent.java
- src/main/java/org/terasology/combatSystem/weaponFeatures/components/ExplosionComponent.java
- src/main/java/org/terasology/combatSystem/weaponFeatures/components/ParentComponent.java
- src/main/java/org/terasology/combatSystem/weaponFeatures/events/MeleeEvent.java
- src/main/java/org/terasology/combatSystem/weaponFeatures/events/PrimaryAttackEvent.java
- src/main/java/org/terasology/combatSystem/weaponFeatures/systems/LaunchEntitySystem.java
- src/main/java/org/terasology/combatSystem/weaponFeatures/systems/MeleeAttackSystem.java
- src/main/java/org/terasology/combatSystem/weaponFeatures/systems/collisionHandling/ExplosionHandlingSystem.java
- src/main/java/org/terasology/combatSystem/weaponFeatures/systems/collisionHandling/StickingHandlingSystem.java
- src/main/java/org/terasology/combatSystem/world/PhysicsRoomRasterizer.java
- src/main/java/org/terasology/combatSystem/world/structures/StructuresHandlingSystem.java
- src/main/java/org/terasology/combatSystem/world/structures/components/AddSwitchDoorsComponent.java
* chore: remove unused imports
* chore: update copyright
> feat(JOML): migrate CombatSystem

- src/main/java/org/terasology/combatSystem/weaponFeatures/systems/LaunchEntitySystem.java
PR: https://github.com/MovingBlocks/Terasology/issues/4500
> feat(JOML): cleanup imports

- src/main/java/org/terasology/combatSystem/world/PhysicsRoomRasterizer.java
Update for https://github.com/MovingBlocks/Terasology/pull/4600.
> Update for engine PR #4600

- module.txt
- src/main/java/org/terasology/combatSystem/hurting/HurtingHandlingSystem.java
- src/main/java/org/terasology/combatSystem/weaponFeatures/systems/LegacyShootSystem.java
- src/main/java/org/terasology/combatSystem/weaponFeatures/systems/collisionHandling/ExplosionHandlingSystem.java
- src/main/java/org/terasology/combatSystem/weaponFeatures/systems/collisionHandling/StickingHandlingSystem.java
- bump version for Health to 2.0.0-SNAPSHOT
- adjust imports (auto-refactoring done by IntelliJ)
Depends on https://github.com/Terasology/Health/pull/78
> refactor: adjust for restructured Health v2.0.0-SNAPSHOT

- src/main/java/org/terasology/combatSystem/inventory/QuiverUIClientSystem.java
PR: https://github.com/MovingBlocks/Terasology/pull/4593
> chore: migrate gestalt v7

- assets/prefabs/basicExplosion.prefab
- assets/prefabs/projectiles/arrows/stickArrow.prefab
- assets/prefabs/projectiles/spearThrow.prefab
- assets/prefabs/traps/fireBallMineTrap.prefab
Depends on https://github.com/Terasology/Health/pull/84
> chore: add BaseRegenComponent, update HealthComponent

- assets/prefabs/items/arrows/bounceArrowItem.prefab
- assets/prefabs/items/arrows/explodeArrowItem.prefab
- assets/prefabs/items/arrows/stickArrowItem.prefab
> fix: arrow cooldown time
